[option]
name = "Static"

[[provider]]
id = "provider"
type = "orientable-with-bottom"
block-id = "minecraft:beehive"
blockstates = [
	{ preset = "rotations" },
	{ key = "honey-level", values = [0, 1, 2, 3, 4, 5] }
]
